### ISSUE TITLE
Sort atoms

### ISSUE THREAD

**Issue by nzbr** [nzbr/vlogsolv#2]
Before printing them (at the beginning or in the table) the array of atoms should be sorted alphabetically.

A good place to implement this would be the `get_atoms` function in `vlogsolv.v`

**Comment by cyucelen** [comment]
Hi can you assign me to the issue?

**Comment by cyucelen** [comment]
What version of V you are using? @nzbr

**Comment by nzbr** [comment]
For me the build fails on the 0.1.21 release because of some error in vlib which got fixed
I build the compiler from the master branch, that should work
